version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # This creates an anonymous volume for node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - db_data:/data

volumes:
  db_data: 