name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 22]  # Example for Node.js versions

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: npm test

    - name: Run ESLint
      run: npm run lint

    - name: Check for secrets
      uses: trufflesecurity/trufflehog@v3.0.0
      with:
        scan: 'git'